import pytest

from transactify import predict_categories
# from .predict_category import predict_categories

new_transactions = [
"Amazon",
"ABC Restaurant",
"Gas station",
"Payment to ABC Corp",
"Grocery at XYZ Mart",
"Clothes at H&M",
"McDonald's",
"Electricity bill",
"Movie ticket",
"Furniture at IKEA",
"Starbucks",
"Car insurance",
"Music subscription",
"Train ticket",
"Pharmacy",
"Netflix",
"Hardware store",
"Magazine renewal",
"Italian Restaurant",
"Phone bill",
"Course subscription",
"Gym membership",
"Walmart",
"Coffee machine",
"Chinese Restaurant",
"Gas bill",
"Gaming console",
"Taxi",
"Barnes & Noble",
"Utility payment",
"Subway",
"Software subscription",
"Bedding",
"Mexican Restaurant",
"Credit card payment",
"Nike",
"Concert ticket",
"Internet bill",
"Target",
"Haircut",
"Spotify",
"Laptop",
"Denny's",
"Streaming service",
"Clothing alteration",
"Charity donation",
"Car wash",
"Sushi Restaurant",
"Phone payment",
"Art supplies",
"Water bill",
"spgroup.com.sg",
"Educative",
"Harry Potter ticket",
"Beach",
"Marina",
"T-shirt",
"Hotel booking",
"Adobe Creative Cloud",
"Food bank donation",
"School supplies",
"Gardening",
"Sports event tickets",
"Car rental",
"Cleaning service",
"Etsy",
"Airline ticket",
"Seafood Restaurant",
"Coding bootcamp",
"New phone",
"Carpet cleaning",
"Health club",
"Produce market",
"Pest control",
"Office supplies",
"Installments",
"Animal shelter donation",
"Accountant",
"Educational toys",
"Sports equipment",
"Parking fee",
"Bakery",
"House painting",
"Airport taxi",
"Language tutor",
"Audible",
"Driving lessons",
"Bike",
"Dance class",
"Custom furniture",
"Window cleaning",
"Musical instrument",
"Environmental donation",
"Water filter",
"Concert memorabilia",
"Video game subscription",
"Cooking class",
"Babysitter",
"New mattress",
"Handmade jewelry",
"Tutoring",
"Photo printing",
"Boat rental",
"Camping gear",
"Meditation app",
"Physiotherapy",
"Fitness app",
"Pet grooming kit",
"Pet insurance",
"Streaming renewal",
"Video editing software",
"Virtual event tickets",
"Digital magazine",
"Fitness subscription",
"Gaming platform",
"Virtual concert tickets",
"Cloud storage",
"Online movie tickets",
"Digital music album",
"Online course",
"Virtual concert",
"Virtual museum",
"Productivity app",
"Digital artwork",
"Weekly groceries",
"Online fitness",
"Virtual theater",
"Video streaming",
]

# Predict categories for new transactions
predicted_categories = predict_categories(new_transactions)

for transaction, category in zip(new_transactions, predicted_categories):
    print(f"Transaction: {transaction} --> Predicted Category: {category}")